// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlKv12QMyGfl3XsCLw5bXTwUu4vMxN9Y4',
    appId: '1:538202085420:web:d3fcec063c6d614d829989',
    messagingSenderId: '538202085420',
    projectId: 'bir-umma-2b741',
    authDomain: 'bir-umma-2b741.firebaseapp.com',
    storageBucket: 'bir-umma-2b741.appspot.com',
    measurementId: 'G-37JJB4W5EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz90yjadVoBb-XKMMCzFHLkYWHliVJ-i0',
    appId: '1:538202085420:android:31b322a4c55dcd7d829989',
    messagingSenderId: '538202085420',
    projectId: 'bir-umma-2b741',
    storageBucket: 'bir-umma-2b741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBysIwKw0XkMUXxoF_Kf-k3emFL7H3fXmA',
    appId: '1:538202085420:ios:6df38ef95b90c0b0829989',
    messagingSenderId: '538202085420',
    projectId: 'bir-umma-2b741',
    storageBucket: 'bir-umma-2b741.appspot.com',
    androidClientId: '538202085420-ljrhenm4869ivjtnhj96bv77idjmkfr8.apps.googleusercontent.com',
    iosClientId: '538202085420-ekrh40qfdiatglmae5nkh4poggo9idff.apps.googleusercontent.com',
    iosBundleId: 'com.example.birUmma',
  );
}
