// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeszW8nYiAh6tfLBCUDIJARnYergqdR2I',
    appId: '1:697433015250:web:87387188642e1cd3057e0b',
    messagingSenderId: '697433015250',
    projectId: 'bir-umma-fae1b',
    authDomain: 'bir-umma-fae1b.firebaseapp.com',
    storageBucket: 'bir-umma-fae1b.appspot.com',
    measurementId: 'G-WQNH698GV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8DxqNB7PNVaAbqePH_17oOWS9kNs5xGo',
    appId: '1:697433015250:android:6b88686cafb3b715057e0b',
    messagingSenderId: '697433015250',
    projectId: 'bir-umma-fae1b',
    storageBucket: 'bir-umma-fae1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDslyVu0vxlvYzwxZqfDSiyP_yusKp1FX4',
    appId: '1:697433015250:ios:36ada286024a2fa6057e0b',
    messagingSenderId: '697433015250',
    projectId: 'bir-umma-fae1b',
    storageBucket: 'bir-umma-fae1b.appspot.com',
    iosBundleId: 'com.example.birUmma',
  );
}
